### ISSUE TITLE
Surah Al-Baqarah Ayah 100 (أَوَكُلَّمَا)

### ISSUE THREAD

**Issue by rrefky** [khaledhosny/quran-data#24] opened 2022-04-18 09:02 UTC
السلام عليكم
There is a space between (أَوَ) and (كُلَّمَا) in Ayah 100 of Surah Al-Baqarah

**Comment by khaledhosny** [comment] 2022-04-18 13:49
Duplicate of #17

**Closed as completed by khaledhosny** 2022-04-18 13:49 UTC
